const base='assets/final/';
const projects={
  catalog:{index:'01 / 04',title:'画册设计',desc:'汽车智能屏、商用显示与 MicroLED 等产品画册和型录设计，通过统一网格、信息层级和场景图建立专业的产品表达。',tags:['CATALOG','EDITORIAL','PRODUCT'],images:['catalog-design.webp']},
  mixed:{index:'02 / 04',title:'杂项视觉设计',desc:'涵盖品牌价值、产品发布、社交媒体、认证信息、节日传播及产品营销海报，展现多种视觉风格和执行能力。',tags:['BRAND VISUAL','CAMPAIGN','SOCIAL'],images:['mixed-visuals.webp']},
  exhibition:{index:'03 / 04',title:'展会设计',desc:'围绕展会场景完成邀请函、产品型录、样品清单、展板、员工名片及活动传播视觉，在不同触点保持品牌一致性。',tags:['EXHIBITION','INVITATION','EVENT'],images:['exhibition-design.webp']},
  detail:{index:'04 / 04',title:'长图详情页设计',desc:'针对智能硬件、车载大屏、照明与消费产品设计电商长图，通过卖点提炼、信息图形和场景呈现推动用户理解。',tags:['DETAIL PAGE','E-COMMERCE','INFOGRAPHIC'],images:['detail-page-design.webp']}
};
const keys=Object.keys(projects),modal=document.querySelector('#project-modal');let activeKey=keys[0];
function showProject(key){const p=projects[key];if(!p)return;activeKey=key;document.querySelector('#modal-title').textContent=p.title;document.querySelector('#modal-index').textContent=p.index;document.querySelector('#modal-desc').textContent=p.desc;document.querySelector('#modal-tags').innerHTML=p.tags.map(x=>`<span>${x}</span>`).join('');document.querySelector('#modal-gallery').innerHTML=p.images.map((x,i)=>`<figure><img src="${base+x}" alt="${p.title}作品图 ${i+1}" loading="lazy"></figure>`).join('');if(!modal.open)modal.showModal();modal.scrollTo({top:0,behavior:'instant'});}
document.querySelectorAll('[data-project]').forEach(el=>{el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();showProject(el.dataset.project);},{capture:true});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();showProject(el.dataset.project);}},{capture:true});});
document.querySelector('.modal-close').addEventListener('click',()=>modal.close());document.querySelector('#next-project').addEventListener('click',()=>showProject(keys[(keys.indexOf(activeKey)+1)%keys.length]));modal.addEventListener('click',e=>{if(e.target===modal)modal.close();});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const orb=document.querySelector('.cursor-orb');window.addEventListener('pointermove',e=>{orb.style.left=`${e.clientX}px`;orb.style.top=`${e.clientY}px`;});document.querySelectorAll('a,button,.work-item').forEach(el=>{el.addEventListener('pointerenter',()=>orb.classList.add('active'));el.addEventListener('pointerleave',()=>orb.classList.remove('active'));});
const stage=document.querySelector('#portfolio-stage'),folder=document.querySelector('.folder'),pupils=document.querySelectorAll('.eye-pupil'),catalogSlot=document.querySelector('.card-1'),catalogCard=document.querySelector('.card-1 .project-card');folder.addEventListener('pointerenter',()=>stage.classList.add('expanded'));stage.addEventListener('pointerleave',()=>{stage.classList.remove('expanded');catalogSlot.classList.remove('is-targeted');});folder.addEventListener('click',()=>stage.classList.toggle('expanded'));stage.addEventListener('pointermove',e=>{const r=catalogCard.getBoundingClientRect(),isOpen=stage.classList.contains('expanded')||stage.classList.contains('fanned'),isOverCatalog=isOpen&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;catalogSlot.classList.toggle('is-targeted',isOverCatalog);});stage.addEventListener('click',e=>{if(!stage.classList.contains('expanded'))return;const r=catalogCard.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){e.preventDefault();e.stopPropagation();showProject('catalog');}},{capture:true});window.addEventListener('pointermove',e=>{if(innerWidth>=800){const x=(e.clientX/innerWidth-.5)*9,y=(e.clientY/innerHeight-.5)*-6;stage.style.setProperty('--stage-ry',`${x}deg`);stage.style.setProperty('--stage-rx',`${y}deg`);}pupils.forEach(pupil=>{const eye=pupil.parentElement.getBoundingClientRect(),dx=e.clientX-(eye.left+eye.width/2),dy=e.clientY-(eye.top+eye.height/2),distance=Math.hypot(dx,dy)||1,limit=4.5;pupil.style.setProperty('--eye-x',`${dx/distance*limit}px`);pupil.style.setProperty('--eye-y',`${dy/distance*limit}px`);});});window.addEventListener('pointerleave',()=>{stage.style.setProperty('--stage-ry','0deg');stage.style.setProperty('--stage-rx','0deg');pupils.forEach(pupil=>{pupil.style.setProperty('--eye-x','0px');pupil.style.setProperty('--eye-y','0px');});});
